apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    app: cart
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cart
  labels:
    app: cart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      initContainers:
        - name: parameters-pull
          image: docker.io/rkalluru/d77-parameter-store-init-container-image
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "150Mi"
              cpu: "100m"
          volumeMounts:
          - mountPath: /parameters
            name: parameters
          env:
            - name: PARAMS
              value: "dev.roboshop.cart.REDIS_HOST,REDIS_HOST dev.roboshop.cart.CATALOGUE_HOST,CATALOGUE_HOST dev.roboshop.cart.CATALOGUE_PORT,CATALOGUE_PORT"
      containers:
        - name: cart
          image: rkalluru/d77-cart
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /parameters
            name: parameters
      volumes:
      - name: parameters
        emptyDir: {}


