apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ .Values.component }}
  labels:
    app: {{ .Values.component }}
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      app: {{ .Values.component }}
  template:
    metadata:
      labels:
        app: {{ .Values.component }}
    spec:
      initContainers:
        - name: parameters-pull
          image: {{ .Values.initContainers.parameters-pull.image }}
          imagePullPolicy: {{ .Values.initContainers.parameters-pull.imagePullPolicy }}
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "150Mi"
              cpu: "100m"
          volumeMounts:
          - mountPath: /parameters
            name: parameters
          env:
            - name: PARAMS
              value: {{ .Values.PARAMS }}
      containers:
        - name: {{ .Values.component }}
          image: {{ .Values.containers.main.image }}
          imagePullPolicy: {{ .Values.containers.main.imagePullPolicy }}
          volumeMounts:
          - mountPath: /parameters
            name: parameters
      volumes:
      - name: parameters
        emptyDir: {}
